
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            7305
     no. of nonzeroes in lower triangle of a =           89247
     no. of nonzeroes in the factor l        =          581096
     ratio of nonzeroes in factor (min/max)  =          0.8618
     number of super nodes                   =             417
     maximum order of a front matrix         =             207
     maximum size of a front matrix          =           21528
     maximum size of a front trapezoid       =           16478
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.6811D+07
     no. of floating point ops for solve     =      1.9894D+06
     ratio of flops for factor (min/max)     =          0.9112
     ratio of allocated memory (max/min)     =          1.1374
     number of positive pivots               =            7305
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001116
     time (cpu & wall) for ordering          =        0.093750        0.086190
     time (cpu & wall) for other matrix prep =        0.015625        0.010726
     time (cpu & wall) for value input       =        0.000000        0.001608
     time (cpu & wall) for matrix distrib.   =        0.000000        0.018178
     time (cpu & wall) for numeric factor    =        0.046875        0.039880
     computational rate (gflops) for factor  =        0.998634        1.173781

     no input or output performed

  Solver Memory allocated on core    0       =        3.088 MB
  Solver Memory allocated on core    1       =        2.966 MB
  Solver Memory allocated on core    2       =        2.843 MB
  Solver Memory allocated on core    3       =        2.715 MB
  Total Solver Memory allocated by all cores =       11.611 MB

